global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['localhost:5001']

remote_write:
  - url: 'http://localhost:8086/api/v1/prom/write?db=monitoring'
