// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"time"
)

type RandomDatum struct {
	ID      int64     `json:"id"`
	X       string    `json:"x"`
	Y       string    `json:"y"`
	Created time.Time `json:"created"`
}
